stages:
  preprocess:
    #cmd: python3 src/preprocess.py
    cmd: python3 src/${params.conf/preprocessor/v1.yaml:preprocessor.script}
    deps:
    - conf/preprocessor
    - data/raw
    - src/preprocess_.py
    - src/preprocess_target_encoding.py
    - src/utils.py
    outs:
    - artifacts/preprocessor
    - data/processed
    params:
    - conf/preprocessor
  split:
    cmd: python3 src/split.py
    deps:
    - conf
    - data/processed
    - src/split.py
    outs:
    - data/split
  train_and_evaluate:
    cmd: python3 src/train_and_evaluate.py
    deps:
    - conf
    - data/split
    - src/train_and_evaluate.py
    outs:
    - artifacts/model/model.joblib
    metrics:
    - artifacts/metrics/metrics.json
  ingest_data:
    cmd: python3 src/ingest_data.py
    deps:
    - conf
    - src/ingest_data.py
    outs:
    - data/raw
