base:
  project: "Kaggle-S5E8-Classification"
  random_state: 42
  target_col: y

data_source:
  raw_dir: data/raw
  train_csv: train.csv
  test_csv: test.csv

processed_data:
  dir: data/processed
  train_csv: train.csv
  test_csv: test.csv

split_data:
  dir: data/split
  train_path: train.csv
  test_path: test.csv
  test_size: 0.2

model:
  name: XGBoostClassifier
  dir: artifacts/model
  params:
    booster: gbtree
    colsample_bytree: 0.6
    eta: 0.3
    gamma: 5
    grow_policy: lossguide
    max_bin: 1023
    max_depth: 9
    max_leaves: 255
    n_estimators: 400
    objective: reg:logistic
    reg_alpha: 1.875
    reg_lambda: 2.5
    subsample: 0.8
    tree_method: hist

metrics:
  dir: artifacts/metrics
  filename: metrics.json