# Main configuration for the project

defaults:
  - model: xgboost
  - preprocessor: v1
  - _self_

base:
  project: "Kaggle-S5E8-Classification"
  random_state: 42
  target_col: y

data_source:
  raw_dir: data/raw
  train_csv: train.csv
  test_csv: test.csv

processed_data:
  dir: data/processed
  train_csv: train.csv
  test_csv: test.csv

split_data:
  dir: data/split
  train_path: train.csv
  test_path: test.csv
  test_size: 0.2

metrics:
  dir: artifacts/metrics
  filename: metrics.json