# conf/model/lightgbm.yaml
name: LGBMClassifier
dir: artifacts/model
filename: model.joblib
final_filename: final_model.joblib
params:
  objective: binary
  metric: auc
  n_estimators: 1000
  learning_rate: 0.05
  num_leaves: 31
  max_depth: -1
  min_child_samples: 20
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42
  n_jobs: -1