# This is the final GitHub Actions workflow that automates the ML pipeline

name: Kaggle Submission CI/CD

# This workflow triggers on any push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build-and-submit:
    runs-on: ubuntu-latest # Use a standard Linux virtual machine

    steps:
      # Step 1: Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set up Kaggle credentials from the GitHub Secret
      - name: Set up Kaggle credentials
        env:
          KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}
        run: |
          mkdir -p ~/.kaggle
          echo "$KAGGLE_JSON" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
      
      # Step 5: Ingest data from Kaggle
      - name: Download and Unzip Kaggle Data
        run: python src/ingest_data.py

      # Step 6: Run the rest of the pipeline
      # This runs the necessary scripts in sequence to produce the submission file
      - name: Preprocess Data, Train Model, and Predict
        run: |
          python src/preprocess.py
          python src/train_final_model.py
          python src/predict.py
      
      # Step 7: Submit to Kaggle
      - name: Submit to Kaggle
        run: python src/submit.py
